pipeline {
    agent any
    environment {
        cluster = 'vvprofileprod'
	    service = 'vproappprodsvc'
    }

    stages {   
	stage('Deploy to ECS staging') {
            steps {
                withAWS(credentials: 'awscreds', region: 'us-east-1') {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                } 
            }
        }    
    }   
}
